### ISSUE TITLE
Temporal_tables 1.0.2 - Argument Errors

### ISSUE THREAD

**Issue by bewatts** [bkroeker/temporal_tables#15]
👋  Still getting Argument Errors in my migrations.  

Gemfile
```
gem "temporal_tables", "~> 1.0.2"
gem "rails", "6.1.4.4"
```

The following bits fail:
`create_table :users, { temporal: true, id: :uuid, default: -> { "gen_random_uuid()" } } do |t|`
`create_table :users, **{ temporal: true, id: :uuid, default: -> { "gen_random_uuid()" } } do |t|`

I also attempted to set the migration version to 6.1, but that didn't do anything.  

Backtrace:
```
wrong number of arguments (given 2, expected 1)
/Users/ben.watts/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/temporal_tables-1.0.2/lib/temporal_tables/temporal_adapter.rb:5:in `create_table'
/Users/ben.watts/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/activerecord-6.1.4.4/lib/active_record/migration.rb:929:in `block in method_missing'
/Users/ben.watts/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/activerecord-6.1.4.4/lib/active_record/migration.rb:897:in `block in say_with_time'
/Users/ben.watts/.rbenv/versions/3.0.3/lib/ruby/3.0.0/benchmark.rb:293:in `measure'
/Users/ben.watts/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/activerecord-6.1.4.4/lib/active_record/migration.rb:897:in `say_with_time'
/Users/ben.watts/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/activerecord-6.1.4.4/lib/active_record/migration.rb:918:in `method_missing'
/Users/ben.watts/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/strong_migrations-0.4.2/lib/strong_migrations/migration.rb:10:in `block in method_missing'
/Users/ben.watts/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/strong_migrations-0.4.2/lib/strong_migrations/checker.rb:173:in `perform'
/Users/ben.watts/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/strong_migrations-0.4.2/lib/strong_migrations/migration.rb:9:in `method_missing'
/Users/ben.watts/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/activerecord-6.1.4.4/lib/active_record/migration/compatibility.rb:36:in `create_table'
/Users/ben.watts/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/activerecord-6.1.4.4/lib/active_record/migration/compatibility.rb:97:in `create_table'
/db/migrate/20190203195356_create_users.rb:4:in `change'
```

**Comment by bkroeker** [comment]
@bewatts I would expect your first line to fail with that error, but your second one should work, or its simpler equivalent:

```ruby
create_table :users, temporal: true, id: :uuid, default: -> { "gen_random_uuid()" } do |t|
```
I tried it myself in both a fresh rails 6.1.4.4 and 7.0.1 project, and it worked fine with the temporal_tables 1.0.2 gem.

**Comment by bewatts** [comment]
Yup, confirmed - this was an issue with an older version of the strong_migrations gem.  Thanks for looking into this.
